version: '3.8'
networks:
    deno-demo:
        name: deno-demo
services: 
    deno-app:
        image: captaaintdocker/deno-demo
        depends_on: 
            - database
        restart: always
        container_name: 'deno-app'
        ports: 
            - 4000:4000
        networks: 
            - deno-demo
    database: 
        image: mongo:latest
        container_name: 'deno_demo_mongo'
        environment: 
            - 'MONGO_INITDB_USERNAME=captaaint'
            - 'MONGO_INITDB_PASSWORD=secret123'
            - 'MONGO_INITDB_DATABASE=deno-demo-db'
        volumes:
            - deno_demo_mongo_data:/data/db
        ports: 
            - 27017:27017
        networks: 
            - deno-demo
volumes: 
    deno_demo_mongo_data: